### ISSUE TITLE
VC4 OpenGL Freeze (RetroArch)

### ISSUE THREAD

**Issue by loganmc10** [raspberrypi/linux#1443]
I am trying to launch an N64 game in RetroArch using the new OpenGL Driver. It locks up, once it does, I can SSH into a new session, but all sorts of commands lock up, including /opt/vc/bin/vcgencmd

This is the GDB backtrace:

(gdb) backtrace
#0 0x76cefa40 in do_futex_wait (isem=isem@entry=0x76a61920 ) at ../nptl/sysdeps/unix/sysv/linux/sem_wait.c:48
#1 0x76cefaf4 in __new_sem_wait (sem=0x76a61920 ) at ../nptl/sysdeps/unix/sysv/linux/sem_wait.c:69
#2 0x76a4aeb4 in dispmanx_send_command () from /opt/vc/lib/libbcm_host.so
#3 0x76a4c500 in vc_dispmanx_update_submit_sync () from /opt/vc/lib/libbcm_host.so
#4 0x0013d3a8 in gfx_ctx_vc_init (video_driver=0x2cf218) at gfx/drivers_context/vc_egl_ctx.c:287
#5 0x0012fe94 in gfx_ctx_init (data=0x2cf218, ctx=0x209284 , ident=0x760e3044 "", api=GFX_CTX_OPENGL_ES_API, major=0, minor=0, hw_render_ctx=false)

at gfx/video_context_driver.c:177
#6 0x00130004 in gfx_ctx_find_driver (data=0x2cf218, ident=0x760e3044 "", api=GFX_CTX_OPENGL_ES_API, major=0, minor=0, hw_render_ctx=false) at gfx/video_context_driver.c:225
#7 0x00130090 in gfx_ctx_init_first (data=0x2cf218, ident=0x760e3044 "", api=GFX_CTX_OPENGL_ES_API, major=0, minor=0, hw_render_ctx=false) at gfx/video_context_driver.c:254
#8 0x00137610 in gl_get_context (gl=0x2cf218) at gfx/drivers/gl.c:2490
#9 0x001376a8 in gl_init (video=0x7effd248, input=0x248eac , input_data=0x248eb0 ) at gfx/drivers/gl.c:2652
#10 0x0003ffcc in init_video () at gfx/video_driver.c:714
#11 0x00041a44 in video_driver_ctl (state=RARCH_DISPLAY_CTL_INIT, data=0x0) at gfx/video_driver.c:1480
#12 0x00044548 in init_drivers (flags=127) at driver.c:330
#13 0x00044948 in driver_ctl (state=RARCH_DRIVER_CTL_INIT, data=0x7effd3c0) at driver.c:456
#14 0x00044964 in driver_ctl (state=RARCH_DRIVER_CTL_INIT_ALL, data=0x0) at driver.c:462
#15 0x000220a0 in rarch_main_init (argc=5, argv=0x7efff734) at retroarch.c:1307
#16 0x00022588 in rarch_ctl (state=RARCH_CTL_MAIN_INIT, data=0x2bf158) at retroarch.c:1437
#17 0x000308f0 in content_load (info=0x7efff5a4) at content.c:878
#18 0x00032954 in content_ctl (state=CONTENT_CTL_LOAD, data=0x7efff5a4) at content.c:1778
#19 0x0001d710 in rarch_main (argc=5, argv=0x7efff734, data=0x0) at frontend/frontend.c:129
#20 0x0001d934 in main (argc=5, argv=0x7efff734) at frontend/frontend.c:184

**Comment by loganmc10** [comment]
I have to reboot to get things like /opt/vc/bin/vcgencmd to work again

Linux raspberrypi 4.4.8-v7+ #880 SMP Fri Apr 22 21:55:04 BST 2016 armv7l GNU/Linux

Firmware:
Apr 24 2016 17:58:59
version e28d96dc23bb499d8c84b22e36dafdd95db20257 (clean) (release)
